"""cria usuarios

Revision ID: 94589b32f45a
Revises: bfbc456245d9
Create Date: 2026-09-22 15:33:52.102668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94589b32f45a'
down_revision: Union[str, Sequence[str], None] = 'bfbc456245d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('usuario_norm', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('nome_responsavel', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('sobrenome', sa.String(), nullable=False),
    sa.Column('aniversario', sa.String(), nullable=False),
    sa.Column('telefone_profissional', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_index(op.f('ix_usuarios_usuario_norm'), 'usuarios', ['usuario_norm'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario_norm'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
