"""cria log_auditoria, log_auditoria_mudanca, historico_cliente

Revision ID: bfbc456245d9
Revises: 
Create Date: 2026-09-16 14:18:14.154481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbc456245d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('usuario_nome', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.String(), nullable=False),
    sa.Column('entidade_nome', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('metadados', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_auditoria_entidade', 'log_auditoria', ['entidade_tipo', 'entidade_id'], unique=False)
    op.create_index(op.f('ix_log_auditoria_timestamp'), 'log_auditoria', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_auditoria_usuario_id'), 'log_auditoria', ['usuario_id'], unique=False)
    op.create_table('historico_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('idcentral', sa.String(), nullable=False),
    sa.Column('cliente_nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('autor_id', sa.String(), nullable=False),
    sa.Column('autor_nome', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('tarefa_id', sa.String(), nullable=True),
    sa.Column('log_auditoria_id', sa.Integer(), nullable=True),
    sa.Column('editavel', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['log_auditoria_id'], ['log_auditoria.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_cliente_cliente_id'), 'historico_cliente', ['cliente_id'], unique=False)
    op.create_index('ix_historico_cliente_timeline', 'historico_cliente', ['cliente_id', 'criado_em'], unique=False)
    op.create_table('log_auditoria_mudanca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_auditoria_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('rotulo', sa.String(), nullable=False),
    sa.Column('valor_de', sa.Text(), nullable=True),
    sa.Column('valor_para', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_auditoria_id'], ['log_auditoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_mudanca_log_auditoria_id'), 'log_auditoria_mudanca', ['log_auditoria_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_auditoria_mudanca_log_auditoria_id'), table_name='log_auditoria_mudanca')
    op.drop_table('log_auditoria_mudanca')
    op.drop_index('ix_historico_cliente_timeline', table_name='historico_cliente')
    op.drop_index(op.f('ix_historico_cliente_cliente_id'), table_name='historico_cliente')
    op.drop_table('historico_cliente')
    op.drop_index(op.f('ix_log_auditoria_usuario_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_timestamp'), table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_entidade', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    # ### end Alembic commands ###
